[WIP]Prepare for release
uniplaces/dynamodbcopy pull request #14
Opened 2019-01-30 16:16 UTC by hfcorreia

- [ ] Add readme documentation
- [ ] Add godoc

2019-01-31 12:39 UTC, raffo0707 approved these changes

2019-02-01 11:31 UTC, jmdalmeida requested changes
Left some suggestions, great job! 💪

2019-02-01 11:31 UTC, jmdalmeida commented on dynamodb.go
> +// NewDynamoClient creates DynamoDB client instance a wrapper around the AWS-SDK with a predefined Session.
```suggestion
// NewDynamoClient creates a DynamoDB client wrapper around the AWS-SDK with a predefined Session.
```

2019-02-01 11:31 UTC, jmdalmeida commented on dynamodb.go
> +// The provided ARN role allows you to configure the Session to ito assume a specific IAM Role.
```suggestion
// The provided ARN role allows you to configure the Session to assume a specific IAM Role.
```

2019-02-01 11:31 UTC, jmdalmeida commented on dynamodb.go
> +// NewDynamoClient creates a new DynamoDBClient to create a session for a given ARN role
remove this as it is the same info as line 34

2019-02-01 11:31 UTC, jmdalmeida commented on dynamodb.go
> +// BatchWrite writes given DynamoDBItem in the DynamoDB table.
```suggestion
// BatchWrite writes the given DynamoDBItem slice into the DynamoDB table.
```

2019-02-01 11:31 UTC, jmdalmeida commented on dynamodb.go
> +// BatchWrite splits the given DynamoDBItem slice in 25 of 25 items.
```suggestion
// The given items will be written in groups of 25 each.
```

2019-02-01 11:31 UTC, jmdalmeida commented on dynamodb.go
> +// If totalSegments is equal to 1, it will a non-parallel scan.
```suggestion
// If totalSegments is equal to 1, it will perform a sequential scan.
```

2019-02-01 11:31 UTC, jmdalmeida commented on sleeper.go
> +// receiving the ms it to sleep, returning the total time it spent sleeping
```suggestion
// receiving the intended sleep time (in ms) and returning the total time spent sleeping
```

2019-02-01 11:31 UTC, jmdalmeida commented on sleeper.go
> +// RandomSleeper will sleep for the provided ms plus an aditional factor (ranging between [0, 100[).
```suggestion
// RandomSleeper will sleep for the provided time (in ms) plus an additional random factor (ranging between [0, 100[).
```

2019-02-01 11:53 UTC, jmdalmeida approved these changes

2019-02-01 11:56 UTC, merged